#!/bin/sh
# Wrapper script to execute Cargo commands against particular crates

BIN="$0"
ARG="$1" ; shift

# In case of empty or flag-only command line, pass through to Cargo directly
if [ -z "$ARG" ] || case $ARG in -*) ;; *) false;; esac; then
    cargo "$ARG" "$@"
    exit $?
fi

# Recognize some common commands and apply them to both crates
case "$ARG" in
    build|check|clean|test)
        for path in ./src/* ; do
            name="$(basename "$path")"
            if [ -d "./src/$name" ]; then
                "$BIN" "$name" "$ARG" "$@" || exit 1
            fi
        done
        exit $?
        ;;
esac

# Otherwise treat the first argument as crate moniker
CRATE="$ARG"
MANIFEST="./src/$CRATE/Cargo.toml"

if [ ! -f "$MANIFEST" ]; then
    echo >&2 "Usage: $BIN CRATE [CARGO_ARGS]"
    exit 2
fi

CMD="$1" ; shift

# Undertake default actions for some crates if no command is given
if [ -z "$CMD" ]; then
    case "$CRATE" in
        server) CMD='run' ;;
    esac
fi

set -x  # echo on
cargo "$CMD" --manifest-path="$MANIFEST" "$@"
